name: Deploy to Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Cloud Foundry CLI
      run: |
        curl -v -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" -o cf.tgz
        tar -xvf cf.tgz
        sudo mv cf /usr/local/bin

    - name: Authenticate to Cloud Foundry
      run: |
        cf api ${{ secrets.CF_API }}
        cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
        cf target -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}

    - name: Deploy to Cloud Foundry
      run: cf push
