name: Deploy to SAP Cloud Foundry

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # - name: Run Tests
      #   run: npm test

      - name: Install Cloud Foundry CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64&source=github" > cf-cli.tgz
          tar -xvf cf-cli.tgz
          sudo mv cf /usr/local/bin/cf

      - name: Set API endpoint
        run: cf api ${{ secrets.CF_SAP_API }}

      - name: Auth with token
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: cf auth "$CF_API_TOKEN"

      - name: Target org and space
        run: cf target -o f3673abbtrial -s dev

      - name: Push app
        run: cf push

      - name: Run Health Check
        run: curl --fail ${{ secrets.CF_API_HEALTH }} 

      
