name: Deploy to SAP Cloud Foundry

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Aquí puedes habilitar tests si los necesitas
      # - name: Run Tests
      #   run: npm test

      - name: Install Cloud Foundry CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable/cf8-cli-installer.sh" -o install.sh
          bash install.sh

      - name: Login to Cloud Foundry
        run: |
          cf api ${{ secrets.CF_API }}
          cf auth "$CF_USERNAME" "$CF_PASSWORD"
          cf target -o f3673abbtrial -s dev

      - name: Push app to CF
        run: cf push

      - name: Run Health Check
        run: curl --fail ${{ secrets.CF_API_HEALTH }}
