name: Deploy to SAP Cloud Foundry

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Aquí puedes habilitar tests si los necesitas
      # - name: Run Tests
      #   run: npm test

      - name: Install Cloud Foundry CLI
        run: |
          wget "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" -O cf-cli.tgz
          mkdir cf-cli
          tar -xvzf cf-cli.tgz -C cf-cli
          sudo mv cf-cli/cf /usr/local/bin/cf
          cf --version

      - name: Login to Cloud Foundry
        run: |
          cf api ${{ secrets.CF_API }}
          cf auth "$CF_USERNAME" "$CF_PASSWORD"
          cf target -o f3673abbtrial -s dev

      - name: Push app to CF
        run: cf push

      - name: Run Health Check
        run: curl --fail ${{ secrets.CF_API_HEALTH }}
